"""fixescnullable to all fks

Revision ID: 1003de9bacf0
Revises: c8bab3f4ff30
Create Date: 2023-09-26 15:06:20.563987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1003de9bacf0'
down_revision: Union[str, None] = 'c8bab3f4ff30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
