"""removes cascade from products

Revision ID: 44ec526f7f9a
Revises: 2c1bdbe87788
Create Date: 2023-09-26 17:08:57.998537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ec526f7f9a'
down_revision: Union[str, None] = '2c1bdbe87788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
