"""adds products

Revision ID: 4ef60b518c29
Revises: 2d1833e2d182
Create Date: 2023-09-20 18:37:34.187002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef60b518c29'
down_revision: Union[str, None] = '2d1833e2d182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('products_owner_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    op.drop_column('products', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_fkey', 'products', 'users', ['owner'], ['id'])
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
