"""sets all delete to all models

Revision ID: aa889592bcbf
Revises: 1003de9bacf0
Create Date: 2023-09-26 16:23:38.396397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa889592bcbf'
down_revision: Union[str, None] = '1003de9bacf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_baskets_products_baskets_id_fkey', 'association_baskets_products', type_='foreignkey')
    op.drop_constraint('association_baskets_products_products_id_fkey', 'association_baskets_products', type_='foreignkey')
    op.create_foreign_key(None, 'association_baskets_products', 'baskets', ['baskets_id'], ['id'])
    op.create_foreign_key(None, 'association_baskets_products', 'products', ['products_id'], ['id'])
    op.drop_constraint('products_owner_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_id_fkey', 'products', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'association_baskets_products', type_='foreignkey')
    op.drop_constraint(None, 'association_baskets_products', type_='foreignkey')
    op.create_foreign_key('association_baskets_products_products_id_fkey', 'association_baskets_products', 'products', ['products_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('association_baskets_products_baskets_id_fkey', 'association_baskets_products', 'baskets', ['baskets_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
