"""removes cascade from baskets and products

Revision ID: bc776f5f25ee
Revises: a3f5c2065431
Create Date: 2023-09-26 17:25:17.580664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc776f5f25ee'
down_revision: Union[str, None] = 'a3f5c2065431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
