"""sets null to all fks

Revision ID: c8bab3f4ff30
Revises: 60d51c7d4b6e
Create Date: 2023-09-26 14:52:22.861541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bab3f4ff30'
down_revision: Union[str, None] = '60d51c7d4b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_baskets_products_baskets_id_fkey', 'association_baskets_products', type_='foreignkey')
    op.drop_constraint('association_baskets_products_products_id_fkey', 'association_baskets_products', type_='foreignkey')
    op.create_foreign_key(None, 'association_baskets_products', 'products', ['products_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'association_baskets_products', 'baskets', ['baskets_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_baskets_products', type_='foreignkey')
    op.drop_constraint(None, 'association_baskets_products', type_='foreignkey')
    op.create_foreign_key('association_baskets_products_products_id_fkey', 'association_baskets_products', 'products', ['products_id'], ['id'])
    op.create_foreign_key('association_baskets_products_baskets_id_fkey', 'association_baskets_products', 'baskets', ['baskets_id'], ['id'])
    # ### end Alembic commands ###
