"""updates basket cascade option

Revision ID: e66d14d0baeb
Revises: 8f6ca012d05a
Create Date: 2023-09-25 18:06:20.274281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66d14d0baeb'
down_revision: Union[str, None] = '8f6ca012d05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
